Update deploy_task.yaml

diff --git a/.tekton/deploy/deploy_task.yaml b/.tekton/deploy/deploy_task.yaml
--- a/.tekton/deploy/deploy_task.yaml
+++ b/.tekton/deploy/deploy_task.yaml
@@ -26,24 +26,25 @@ spec:
           value: $(params.localrun_aes_key)
       command: ["/bin/bash", "-c"]
       args:
-        - set -e -o pipefail;
+        - |
+          set -e -o pipefail;
           echo "Hey $LOCALRUN"
           echo "Deploying to $CLUSTER";
       
           echo "\"ibm_toolchain_pipeline_devsecops_core_git_clone_time_summary\":{\"ibm_toolchain_pipeline_devsecops_time\":\"test\"}";
-          echo "ibm_toolchain_pipeline_devsecops_core_change_request_process_time_summary: { "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}"
-          echo "ibm_toolchain_pipeline_devsecops_core_pipeline_evaluation_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "ibm_toolchain_pipeline_devsecops_pipeline_type" : "pr", "value": "7"}" 
-          echo "ibm_toolchain_pipeline_devsecops_pipeline_info": "{ "ibm_toolchain_pipeline_devsecops_branch": "fix/v10-master-image-update", "ibm_toolchain_pipeline_devsecops_pipeline_type": "ci", "value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_artifact_upload_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_locker_evidence_summary_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_locker_evidence_publish_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_inventory_get_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_commands_count": "{"value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_commands_success_count": "{"value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_commands_error_count": "{"value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_api_calls_count": "{"value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_github_api_calls_count": "{"value": "1"}"
-          echo "ibm_toolchain_pipeline_devsecops_cli_cos_api_call_count": "{"value": "1"}"
+          echo "ibm_toolchain_pipeline_devsecops_core_change_request_process_time_summary: { "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}";
+          echo "ibm_toolchain_pipeline_devsecops_core_pipeline_evaluation_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "ibm_toolchain_pipeline_devsecops_pipeline_type" : "pr", "value": "7"}"; 
+          echo "ibm_toolchain_pipeline_devsecops_pipeline_info": "{ "ibm_toolchain_pipeline_devsecops_branch": "fix/v10-master-image-update", "ibm_toolchain_pipeline_devsecops_pipeline_type": "ci", "value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_artifact_upload_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_locker_evidence_summary_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_locker_evidence_publish_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_inventory_get_time_summary": "{ "ibm_toolchain_pipeline_devsecops_time": "165961", "value": "7"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_commands_count": "{"value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_commands_success_count": "{"value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_commands_error_count": "{"value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_api_calls_count": "{"value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_github_api_calls_count": "{"value": "1"}";
+          echo "ibm_toolchain_pipeline_devsecops_cli_cos_api_call_count": "{"value": "1"}";
           
           echo "Oh and $ANOTHERV";
           sleep 10s;
